name: CI/CD Pipeline for Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install Dependencies
        run: |
          pip install behave selenium requests webdriver-manager behave-html-report

      - name: Run Use Case 1 Tests
        run: behave --tags=usecase1

      - name: Run Use Case 2 Tests
        run: behave --tags=usecase2

      - name: Generate HTML Test Report
        run: behave --junit --outfile=reports

      - name: Convert JUnit to HTML
        run: behave-html-report -i reports -o reports/html_report.html

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: reports/html_report.html
